/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./components/AddTodo.vue')['default']
    IncButton: typeof import('./components/IncButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./components/TodoItem.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
  }
}
